<?php
add_action('acf/include_fields', function () {
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_66ec85896ecc4',
        'title' => 'Add A New Experience Here!',
        'fields' => array(
            array(
                'key' => 'field_66ec858c6a07b',
                'label' => 'Title of Creative Work',
                'name' => 'title_of_creative_work',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_67114728e7dc0',
                'label' => 'In Wikidata?',
                'name' => 'in_wikidata',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => 'Please search at Wikidata.org to find if the creative work that prompted your experience has been added to Wikidata. If you enter "yes," you will be prompted to share the Wikidata Q Identifier',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'acf_ct_read_only_field' => 0,
                'choices' => array(
                    'yes' => 'yes',
                    'no' => 'no',
                ),
                'default_value' => false,
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_66ec85b50b8f1',
                'label' => 'Wikidata QID',
                'name' => 'wikidata-qid',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Enter the number that begins with a Q (the Wikidata Q Identifier) in this field.',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_67114728e7dc0',
                            'operator' => '==contains',
                            'value' => 'yes',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'acf_ct_read_only_field' => 0,
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6787eea156392',
                'label' => 'Wikidata',
                'name' => 'wikidata',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => 'This field is not editable and is only shown for debugging purposes.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
                'readonly' => 1,
            ),
            array(
                'key' => 'field_6787eec056393',
                'label' => 'Wikidata Last Update',
                'name' => 'wikidata_last_update',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'This field is not editable and is only shown for debugging purposes.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'readonly' => 1,
            ),
            array(
                'key' => 'field_671148110ccca',
                'label' => 'URL',
                'name' => 'url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => 'Please enter a URL for the creative work prompting your experience (or a link to a website describing the work)',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_67114728e7dc0',
                            'operator' => '==',
                            'value' => 'no',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'acf_ct_read_only_field' => 0,
                'default_value' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_66ec85cae24cf',
                'label' => 'Experience',
                'name' => 'experience',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => 'Which term below best captures the experience you are submitting? (you can refer to the glossary of experiences for descriptions of each term) If your experience isn\'t in our list, select "xxx-I need to enter something new" at the bottom of the list.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'experience',
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(),
            ),
            array(
                'key' => 'field_67114a3153e2e',
                'label' => 'Propose Experience',
                'name' => 'propose_experience',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => 'What experience do you want to add to our database?',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66ec85cae24cf',
                            'operator' => '==',
                            'value' => '12',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'taxonomy' => 'user-proposed-experience',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'field_type' => 'select',
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(),
            ),
            array(
                'key' => 'field_67114b6af1aa0',
                'label' => 'Define Proposed Experience',
                'name' => 'define_proposed_experienced',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Please define this experience in one or two sentences.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66ec85cae24cf',
                            'operator' => '==',
                            'value' => '12',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'acf_ct_read_only_field' => 0,
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_67114bbaec08e',
                'label' => 'Year of Experience',
                'name' => 'Year_of_Experience',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => 'In what year did you have this experience? Make your best guess if you\'re not totally sure.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'acf_ct_read_only_field' => 0,
                'default_value' => '',
                'min' => '',
                'max' => '',
                'allow_in_bindings' => 1,
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_67114c32bc63d',
                'label' => 'Feature',
                'name' => 'feature',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => 'Please provide a specific feature or combination of features from the creative work that you believe prompted the experience you are entering. If it’s specific language, include direct quotation (with quotation marks). If it is something that can’t be quoted (some aspect of the plot or non-textual features), put it into your own words with as much detail as possible.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'acf_ct_read_only_field' => 0,
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_66ec85dc26aeb',
                'label' => 'Technology',
                'name' => 'technology',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => 'Which term below best captures the technology that prompted your experience? (you can refer to the glossary of technologies for descriptions of each term) If your experience isn\'t in our list, select "xxx-I need to enter something new" at the bottom of the list. If you think your experience was prompted by a combination of technologies, please propose a new term combining two or more.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'technology',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(),
            ),
            array(
                'key' => 'field_67114d369d673',
                'label' => 'Propose Technology',
                'name' => 'propose_technology',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => 'What technique do you want to add to our database?',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66ec85dc26aeb',
                            'operator' => '==',
                            'value' => '197',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'user-proposed-technology',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'multi_select',
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(),
            ),
            array(
                'key' => 'field_67114e2acd6f8',
                'label' => 'Define Proposed Technology',
                'name' => 'define_proposed_technology',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Please define this technology in one or two sentences.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66ec85dc26aeb',
                            'operator' => '==',
                            'value' => '197',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_67114e6d0612c',
                'label' => 'Benefit of Experience',
                'name' => 'benefit_of_experience',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => 'Do you think this experience prompted any of the benefits below? (you can refer to the benefits glossary for description of each term). You can also leave this blank in you\'re not sure. 

Remember that some benefits are immediate and some emerge upon reflection. 

If the benefit isn\'t in our list, select "xxx-I need to enter something new."',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'benefit',
                'add_term' => 0,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(),
            ),
            array(
                'key' => 'field_671150d42e328',
                'label' => 'Propose Benefit',
                'name' => 'propose_benefit',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => 'What benefit do you want to add to our database?',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_67114e6d0612c',
                            'operator' => '==',
                            'value' => '15',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'taxonomy' => 'user-proposed-benefit',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'select',
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'bidirectional' => 0,
                'multiple' => 0,
                'bidirectional_target' => array(),
            ),
            array(
                'key' => 'field_671151db4280d',
                'label' => 'Theorize Benefit',
                'name' => 'theorize_benefit',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => 'If you think this experience was beneficial to you and/or might be beneficial to others, why do you think that is? This is a space to theorize a little about benefits that might emerge from the experience you\'re submitting. Make sure to include citations for any sources you reference as you formulate your hypothesis. You can leave this blank if you\'re not sure.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acf_ct_exclude_column' => 0,
                'acf_ct_read_only_field' => 0,
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'user-experience',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 1,
    ));
});

add_action('init', function () {
    register_taxonomy('benefit', array(
        0 => '',
    ), array(
        'labels' => array(
            'name' => 'Benefits',
            'singular_name' => 'Benefit',
            'menu_name' => 'Benefit',
            'all_items' => 'All Benefit',
            'edit_item' => 'Edit Benefit',
            'view_item' => 'View Benefit',
            'update_item' => 'Update Benefit',
            'add_new_item' => 'Add New Benefit',
            'new_item_name' => 'New Benefit Name',
            'search_items' => 'Search Benefit',
            'popular_items' => 'Popular Benefit',
            'separate_items_with_commas' => 'Separate benefit with commas',
            'add_or_remove_items' => 'Add or remove benefit',
            'choose_from_most_used' => 'Choose from the most used benefit',
            'not_found' => 'No benefit found',
            'no_terms' => 'No benefit',
            'items_list_navigation' => 'Benefit list navigation',
            'items_list' => 'Benefit list',
            'back_to_items' => '← Go to benefit',
            'item_link' => 'Benefit Link',
            'item_link_description' => 'A link to a benefit',
        ),
        'public' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
        'show_admin_column' => true,
    ));

    register_taxonomy('experience', array(
        0 => '',
    ), array(
        'labels' => array(
            'name' => 'Experiences',
            'singular_name' => 'Experience',
            'menu_name' => 'Experiences',
            'all_items' => 'All Experiences',
            'edit_item' => 'Edit Experience',
            'view_item' => 'View Experience',
            'update_item' => 'Update Experience',
            'add_new_item' => 'Add New Experience',
            'new_item_name' => 'New Experience Name',
            'search_items' => 'Search Experiences',
            'popular_items' => 'Popular Experiences',
            'separate_items_with_commas' => 'Separate experiences with commas',
            'add_or_remove_items' => 'Add or remove experiences',
            'choose_from_most_used' => 'Choose from the most used experiences',
            'not_found' => 'No experiences found',
            'no_terms' => 'No experiences',
            'items_list_navigation' => 'Experiences list navigation',
            'items_list' => 'Experiences list',
            'back_to_items' => '← Go to experiences',
            'item_link' => 'Experience Link',
            'item_link_description' => 'A link to a experience',
        ),
        'public' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
        'show_admin_column' => true,
    ));

    register_taxonomy('technology', array(
        0 => '',
    ), array(
        'labels' => array(
            'name' => 'Technologies',
            'singular_name' => 'Technology',
            'menu_name' => 'Technologies',
            'all_items' => 'All Technologies',
            'edit_item' => 'Edit Technology',
            'view_item' => 'View Technology',
            'update_item' => 'Update Technology',
            'add_new_item' => 'Add New Technology',
            'new_item_name' => 'New Technology Name',
            'search_items' => 'Search Technologies',
            'popular_items' => 'Popular Technologies',
            'separate_items_with_commas' => 'Separate technologies with commas',
            'add_or_remove_items' => 'Add or remove technologies',
            'choose_from_most_used' => 'Choose from the most used technologies',
            'not_found' => 'No technologies found',
            'no_terms' => 'No technologies',
            'items_list_navigation' => 'Technologies list navigation',
            'items_list' => 'Technologies list',
            'back_to_items' => '← Go to technologies',
            'item_link' => 'Technology Link',
            'item_link_description' => 'A link to a technology',
        ),
        'public' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
        'show_admin_column' => true,
    ));

    register_taxonomy('user-proposed-benefit', array(
        0 => '',
    ), array(
        'labels' => array(
            'name' => 'User-Proposed Benefits',
            'singular_name' => 'User-Proposed Benefit',
            'menu_name' => 'User-Proposed Benefits',
            'all_items' => 'All User-Proposed Benefits',
            'edit_item' => 'Edit User-Proposed Benefit',
            'view_item' => 'View User-Proposed Benefit',
            'update_item' => 'Update User-Proposed Benefit',
            'add_new_item' => 'Add New User-Proposed Benefit',
            'new_item_name' => 'New User-Proposed Benefit Name',
            'search_items' => 'Search User-Proposed Benefits',
            'popular_items' => 'Popular User-Proposed Benefits',
            'separate_items_with_commas' => 'Separate user-proposed benefits with commas',
            'add_or_remove_items' => 'Add or remove user-proposed benefits',
            'choose_from_most_used' => 'Choose from the most used user-proposed benefits',
            'not_found' => 'No user-proposed benefits found',
            'no_terms' => 'No user-proposed benefits',
            'items_list_navigation' => 'User-Proposed Benefits list navigation',
            'items_list' => 'User-Proposed Benefits list',
            'back_to_items' => '← Go to user-proposed benefits',
            'item_link' => 'User-Proposed Benefit Link',
            'item_link_description' => 'A link to a user-proposed benefit',
        ),
        'public' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
        'show_admin_column' => true,
    ));

    register_taxonomy('user-proposed-experience', array(
        0 => '',
    ), array(
        'labels' => array(
            'name' => 'User-Proposed Experiences',
            'singular_name' => 'User-Proposed Experience',
            'menu_name' => 'User Proposed Experiences',
            'all_items' => 'All User Proposed Experiences',
            'edit_item' => 'Edit User Proposed Experience',
            'view_item' => 'View User Proposed Experience',
            'update_item' => 'Update User Proposed Experience',
            'add_new_item' => 'Add New User Proposed Experience',
            'new_item_name' => 'New User Proposed Experience Name',
            'search_items' => 'Search User Proposed Experiences',
            'popular_items' => 'Popular User Proposed Experiences',
            'separate_items_with_commas' => 'Separate user proposed experiences with commas',
            'add_or_remove_items' => 'Add or remove user proposed experiences',
            'choose_from_most_used' => 'Choose from the most used user proposed experiences',
            'not_found' => 'No user proposed experiences found',
            'no_terms' => 'No user proposed experiences',
            'items_list_navigation' => 'User Proposed Experiences list navigation',
            'items_list' => 'User Proposed Experiences list',
            'back_to_items' => '← Go to user proposed experiences',
            'item_link' => 'User Proposed Experience Link',
            'item_link_description' => 'A link to a user proposed experience',
        ),
        'public' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
        'show_admin_column' => true,
    ));

    register_taxonomy('user-proposed-technology', array(
        0 => '',
    ), array(
        'labels' => array(
            'name' => 'User-Proposed Technologies',
            'singular_name' => 'User-Proposed Technology',
            'menu_name' => 'User-Proposed Technologies',
            'all_items' => 'All User-Proposed Technologies',
            'edit_item' => 'Edit User-Proposed Technology',
            'view_item' => 'View User-Proposed Technology',
            'update_item' => 'Update User-Proposed Technology',
            'add_new_item' => 'Add New User-Proposed Technology',
            'new_item_name' => 'New User-Proposed Technology Name',
            'search_items' => 'Search User-Proposed Technologies',
            'popular_items' => 'Popular User-Proposed Technologies',
            'separate_items_with_commas' => 'Separate user-proposed technologies with commas',
            'add_or_remove_items' => 'Add or remove user-proposed technologies',
            'choose_from_most_used' => 'Choose from the most used user-proposed technologies',
            'not_found' => 'No user-proposed technologies found',
            'no_terms' => 'No user-proposed technologies',
            'items_list_navigation' => 'User-Proposed Technologies list navigation',
            'items_list' => 'User-Proposed Technologies list',
            'back_to_items' => '← Go to user-proposed technologies',
            'item_link' => 'User-Proposed Technology Link',
            'item_link_description' => 'A link to a user-proposed technology',
        ),
        'public' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
        'show_admin_column' => true,
    ));
});

add_action('init', function () {
    register_post_type('discussion-reflectio', array(
        'labels' => array(
            'name' => 'Discussion Reflections',
            'singular_name' => 'Discussion Reflection',
            'menu_name' => 'Discussion Reflections',
            'all_items' => 'All Discussion Reflections',
            'edit_item' => 'Edit Discussion Reflection',
            'view_item' => 'View Discussion Reflection',
            'view_items' => 'View Discussion Reflections',
            'add_new_item' => 'Add New Discussion Reflection',
            'add_new' => 'Add New Discussion Reflection',
            'new_item' => 'New Discussion Reflection',
            'parent_item_colon' => 'Parent Discussion Reflection:',
            'search_items' => 'Search Discussion Reflections',
            'not_found' => 'No discussion reflections found',
            'not_found_in_trash' => 'No discussion reflections found in Trash',
            'archives' => 'Discussion Reflection Archives',
            'attributes' => 'Discussion Reflection Attributes',
            'insert_into_item' => 'Insert into discussion reflection',
            'uploaded_to_this_item' => 'Uploaded to this discussion reflection',
            'filter_items_list' => 'Filter discussion reflections list',
            'filter_by_date' => 'Filter discussion reflections by date',
            'items_list_navigation' => 'Discussion Reflections list navigation',
            'items_list' => 'Discussion Reflections list',
            'item_published' => 'Discussion Reflection published.',
            'item_published_privately' => 'Discussion Reflection published privately.',
            'item_reverted_to_draft' => 'Discussion Reflection reverted to draft.',
            'item_scheduled' => 'Discussion Reflection scheduled.',
            'item_updated' => 'Discussion Reflection updated.',
            'item_link' => 'Discussion Reflection Link',
            'item_link_description' => 'A link to a discussion reflection.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-admin-post',
        'supports' => array(
            0 => 'title',
            1 => 'editor',
            2 => 'thumbnail',
            3 => 'custom-fields',
        ),
        'taxonomies' => array(
            0 => 'category',
        ),
        'delete_with_user' => false,
    ));

    register_post_type('user-experience', array(
        'labels' => array(
            'name' => 'User Experiences',
            'singular_name' => 'User Experience',
            'menu_name' => 'User Experiences',
            'all_items' => 'All User Experiences',
            'edit_item' => 'Edit User Experience',
            'view_item' => 'View User Experience',
            'view_items' => 'View User Experiences',
            'add_new_item' => 'Add New User Experience',
            'add_new' => 'Add New User Experience',
            'new_item' => 'New User Experience',
            'parent_item_colon' => 'Parent User Experience:',
            'search_items' => 'Search User Experiences',
            'not_found' => 'No user experiences found',
            'not_found_in_trash' => 'No user experiences found in Trash',
            'archives' => 'User Experience Archives',
            'attributes' => 'User Experience Attributes',
            'insert_into_item' => 'Insert into user experience',
            'uploaded_to_this_item' => 'Uploaded to this user experience',
            'filter_items_list' => 'Filter user experiences list',
            'filter_by_date' => 'Filter user experiences by date',
            'items_list_navigation' => 'User Experiences list navigation',
            'items_list' => 'User Experiences list',
            'item_published' => 'User Experience published.',
            'item_published_privately' => 'User Experience published privately.',
            'item_reverted_to_draft' => 'User Experience reverted to draft.',
            'item_scheduled' => 'User Experience scheduled.',
            'item_updated' => 'User Experience updated.',
            'item_link' => 'User Experience Link',
            'item_link_description' => 'A link to a user experience.',
        ),
        'public' => false,
        'exclude_from_search' => false,
        'publicly_queryable' => true,
        'show_ui' => true,
        'show_in_nav_menus' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-admin-post',
        'supports' => array(
            0 => 'title',
            1 => 'author',
            2 => 'editor',
            3 => 'thumbnail',
            4 => 'custom-fields',
        ),
        'taxonomies' => array(
            0 => 'user-proposed-experience',
            1 => 'user-proposed-technology',
            2 => 'user-proposed-benefit',
            3 => 'experience',
            4 => 'technology',
            5 => 'benefit',
        ),
        'has_archive' => 'user-experience',
        'rewrite' => array(
            'feeds' => false,
        ),
        'delete_with_user' => false,
    ));
});


add_filter('enter_title_here', function ($default, $post) {
    switch ($post->post_type) {
        case 'user-experience':
            return '[Experience] in [Title of Creative Work]';
    }

    return $default;
}, 10, 2);
